CREATE TABLE IF NOT EXISTS "Category" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    icon VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "Category" (name, sort_order)
SELECT DISTINCT category, 0
FROM "Book"
WHERE category IS NOT NULL AND category != ''
ON CONFLICT (name) DO NOTHING;

SELECT * FROM "Category" ORDER BY id;
